# Generated by Django 5.0.4 on 2024-09-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_thread_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='creator',
            new_name='author',
        ),
    ]
